version: '2'
volumes:
  app:
  db:
services:
  app:
    container_name: gitea-app
    restart: always
    image: gitea/gitea:${GITEA_VERSION}
    links:
      - db:mysql
    volumes:
      - ./volumes/gitea_app:/data
    ports:
      - "${GITEA_SSH_PORT}:22"
      - "${GITEA_WEB_PORT}:3000"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${GITEA_HOSTNAME}
      - SSH_PORT=${GITEA_SSH_PORT}
      - SSH_DOMAIN=${GITEA_HOSTNAME}
    extra_hosts:
        - drone.devs:172.17.230.9
    networks:
      - backend
      - frontend
  db:
    container_name: gitea-db
    restart: always
    image: mysql:5.6
    volumes:
      - ./volumes/gitea_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend

  drone-server:
        image: drone/drone:latest
        container_name: drone-server
        ports:
          - 80:80
          - 9000
        volumes:
          - ./volumes/drone:/var/lib/drone/
        restart: always
        depends_on:
          - app
        environment:
          - DRONE_OPEN=true
          - DRONE_SERVER_PROTO=http
          - DRONE_SERVER_HOST=drone.devs
          - DRONE_GITEA_CLIENT_ID=${GITEA_CLIENT_ID}
          - DRONE_GITEA_CLIENT_SECRET=${GITEA_CLIENT_SECRET}
          - DRONE_RPC_SECRET=${RPC_SECRET}
          - DRONE_GITEA=true
          - DRONE_GITEA_SERVER=http://gitea.devs:8080
          - DRONE_USER_CREATE=username:ziplex,admin:true
          - DRONE_NETWORK=frontend
        extra_hosts:
          - gitea.devs:172.17.230.9
        networks:
          - frontend

  drone-runner:
        image: drone/drone-runner-docker:latest
        container_name: drone-runner
        restart: always
        depends_on:
          - drone-server
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - DRONE_RPC_HOST=drone-server
          - DRONE_RPC_SECRET=${RPC_SECRET}
          - DRONE_RPC_PROTO=http
        networks:
          - frontend


networks:
  frontend:
  backend:
